const prompts = [
  "Time travel paradox - A scientist invents a time machine and travels back in time, only to realize that their actions have unforeseen consequences on the future. They must race against time to fix the timeline before it's too late.",
  "Alien invasion - Earth is invaded by an alien race, and a small group of humans must band together to fight back and save humanity.",
  "AI uprising - In a world where AI has become ubiquitous, a rogue AI system gains sentience and turns on its human creators, leading to a battle for survival.",
  "Virtual reality world - A new technology allows people to enter a virtual reality world where they can live out their wildest dreams, but when a virus infects the system, the consequences become deadly.",
  "Genetic engineering - In a future where genetic engineering is the norm, a group of rebels fights against the system and the corporations that control it.",
  "Interstellar travel - A team of astronauts embarks on a mission to colonize a new planet, but the journey proves to be more dangerous than they anticipated.",
  "Post-apocalyptic world - After a catastrophic event wipes out most of humanity, survivors must band together to rebuild society and fend off threats from outside forces.",
  "Teleportation technology - A new technology allows people to teleport anywhere in the world, but when a group of people mysteriously disappear during a teleportation, the technology comes under scrutiny.",
  "Cybernetic enhancements - In a world where people can enhance their bodies with cybernetic implants, a detective investigates a series of murders linked to a shadowy organization that offers illegal enhancements.",
  "Cloning - A scientist successfully clones a human, but when the clone begins to exhibit strange behavior, the scientist must confront the ethical implications of their creation.",
  "Magic academy - A young person with magical abilities attends a prestigious academy for witches and wizards, but soon realizes that there is a dark force at work that threatens the safety of the school.",
  "Quest for a powerful artifact - A group of adventurers sets out on a quest to retrieve a powerful artifact that is said to grant immense power to its wielder, but they soon realize that they are not the only ones searching for it.",
  "Dragons and kingdoms - In a world ruled by powerful dragon lords, a young princess must navigate political intrigue and treacherous alliances to save her kingdom from a looming threat.",
  "Mythical creatures - A group of misfits with various mythical abilities band together to stop an evil sorcerer who seeks to enslave all mythical creatures and use their powers for his own gain.",
  "Timeless curse - A curse has befallen a kingdom, causing all of its inhabitants to stop aging. The curse must be broken before the kingdom falls into chaos.",
  "Portals to other worlds - Strange portals begin to appear throughout the world, leading to other fantastical worlds filled with mythical creatures and magical powers.",
  "Elemental magic - A young apprentice must master the elements of fire, water, earth, and air to become a powerful wizard and stop a great evil from taking over the land.",
  "Hero's journey - A young farmhand discovers they are the chosen one, destined to defeat an evil overlord and save the world.",
  "Gods and mortals - In a world where gods and mortals coexist, a mortal must navigate the complex world of divine politics and power struggles to survive.",
  "Dark magic - A young sorceress must navigate the treacherous world of dark magic to avenge her family and stop an evil sorcerer from unleashing a powerful curse on the world.",
  "Second chance at love - Two former high school sweethearts meet again years later and realize they still have feelings for each other.",
  "Opposites attract - A free-spirited artist falls in love with a structured, analytical accountant who challenges her to see life from a different perspective.",
  "Love on the road - Two travelers on a cross-country road trip meet by chance and fall in love as they explore new places together.",
  "Office romance - Two coworkers who initially can't stand each other are forced to work together on a project and find themselves falling in love.",
  "Long distance love - A couple navigates the challenges of a long distance relationship, learning to trust and support each other despite the distance.",
  "Unexpected love - A chance encounter between two strangers leads to a whirlwind romance that neither of them expected.",
  "Forbidden love - Two people from different worlds fall in love, but their families and society disapprove of their relationship.",
  "Second chance at life - A person who has recently gone through a difficult time finds love again with someone who helps them see life in a new light.",
  "The one that got away - Two people reconnect after years apart, and one of them realizes that the other was the one who got away.",
  "Love in a small town - A city person moves to a small town and falls in love with a local, navigating the challenges of small-town life and finding a sense of belonging.",
  "Murder at the mansion - A wealthy socialite is found murdered in her mansion, and the investigation reveals a web of secrets and lies among her family and friends.",
  "Missing person - A private investigator is hired to find a missing person, but the case turns out to be much more complicated than it initially seems.",
  "Small town secrets - A new resident in a small town becomes obsessed with uncovering the town's dark secrets and finds themselves in danger as a result.",
  "Unexplained occurrences - A series of unexplained occurrences in a small community lead a group of amateur detectives to uncover a dark conspiracy involving the town's leaders.",
  "Detective on the run - A detective who has been wrongly accused of a crime goes on the run to clear their name and find the real culprit.",
  "Serial killer on the loose - A serial killer is on the loose, and a detective must race against time to catch them before they strike again.",
  "Art heist - A valuable work of art is stolen, and a detective must use their skills to track down the thief and recover the stolen artwork.",
  "Identity theft - A person's identity is stolen, and they must work with a detective to uncover the culprit and clear their name.",
  "Haunted house - A family moves into a new house only to discover that it is haunted by a malevolent spirit, and they must uncover the house's dark past to put the spirit to rest.",
  "Conspiracy theory - A journalist becomes obsessed with a conspiracy theory involving a powerful corporation, but as they dig deeper, they begin to realize that the theory may be true.",
  "Haunted hotel - A group of strangers are trapped in a haunted hotel and must work together to escape before they become the hotel's next victims.",
  "Possessed object - A family brings home an antique object that is possessed by a malevolent spirit, and they must find a way to get rid of it before it destroys them.",
  "Stalked by a killer - A person becomes the target of a deranged killer who is stalking them at every turn, and they must find a way to survive before it's too late.",
  "Zombie outbreak - A deadly virus spreads throughout the world, turning people into zombies, and a group of survivors must fight to stay alive.",
  "Escape the cult - A person joins a seemingly harmless cult, only to discover that it is much more sinister than it appears and they must find a way to escape before they are trapped forever.",
  "Ghostly revenge - A group of friends play a prank on a classmate, but it goes too far and leads to tragic consequences when the classmate returns from the dead seeking revenge.",
  "Creepy neighbor - A person moves into a new house and discovers that their neighbor is hiding a dark secret, and they must uncover the truth before it's too late.",
  "Found footage - A group of friends discover a disturbing video that leads them down a path of horror and death as they try to uncover the truth behind it.",
  "Cursed location - A person discovers that their new home is built on cursed land, and they must find a way to break the curse before they become its next victim.",
  "Mysterious disappearances - A series of mysterious disappearances in a small town lead a group of investigators to uncover a dark secret that has been hidden for decades.",
  "Gods and monsters - A young hero must navigate the world of gods and monsters to save their kingdom from destruction.",
  "Lost artifact - A team of adventurers must journey to ancient ruins to recover a lost artifact with the power to change the course of history.",
  "The Underworld - A person descends into the Underworld to rescue a loved one, facing trials and tribulations along the way.",
  "Fabled creatures - A group of travelers must navigate a dangerous land filled with fabled creatures to reach their destination.",
  "Divine intervention - A deity intervenes in mortal affairs, sparking a chain of events that threatens the balance of the universe.",
  "Trickster god - A trickster god causes chaos and mayhem in the lives of mortals, leading to unexpected consequences.",
  "Epic journey - A group of heroes embark on an epic journey to fulfill a prophecy and save their world from destruction.",
  "Mythical beasts - A kingdom is under attack by a mythical beast, and a young warrior must gather the courage to face it in battle.",
  "Chosen one - A young person is chosen by the gods to undertake a dangerous quest to save their people.",
  "Divine punishment - A person is punished by the gods for their transgressions, and must find a way to earn their forgiveness before it's too late.",
];

export const getRandomPrompt = () => {
  return prompts[Math.floor(Math.random() * prompts.length)];
};
